### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by aepstein** [aepstein/vumt#53]
One of 6 core i18n languages in NYS - locale is es

**Comment by natastro** [comment]
Happy to help with Spanish translations if needed! Thank you!

**Comment by aepstein** [comment]
Thank you, @natastro!

I set up a new branch i18n_es you can fork.  All the prompts for server-side operations are in lib/locales/es and the client-side prompts are in client/src/locales/es.js. Please submit a PR against that branch to contribute back to the project when done.

Let me know any questions you have.
